version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    ports:
      - "50051:50051"
    networks:
      - skibiribab
  client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    depends_on:
      - server
    networks:
      - skibiribab
networks:
  skibiribab:
